export const dummyitems = [
  {
    id: 1,
    title: "iPhone 14 Pro",
    description: "Black iPhone found near library",
    location: "Main Library",
    date: "2024-01-15",
    image: "https://placehold.co/300x200/4318D1/FFFFFF?text=iPhone",
    status: "found",
    contact: "john@university.edu",
  },
  {
    id: 2,
    title: "Blue Backpack",
    description: "Nike backpack with textbooks inside",
    location: "Student Center",
    date: "2024-01-14",
    image: "https://placehold.co/300x200/059669/FFFFFF?text=Backpack",
    status: "lost",
    contact: "sarah@university.edu",
  },
  {
    id: 3,
    title: "Silver MacBook",
    description: "MacBook Air with university stickers",
    location: "Engineering Building",
    date: "2024-01-13",
    image: "https://placehold.co/300x200/DC2626/FFFFFF?text=MacBook",
    status: "found",
    contact: "mike@university.edu",
  },
  {
    id: 4,
    title: "Black Leather Wallet",
    description: "Wallet with ID and credit cards",
    location: "Campus Cafeteria",
    date: "2024-01-12",
    image: "https://placehold.co/300x200/000000/FFFFFF?text=Wallet",
    status: "lost",
    contact: "alice@university.edu",
  },
  {
    id: 5,
    title: "Green Water Bottle",
    description: "Stainless steel water bottle",
    location: "Gym",
    date: "2024-01-11",
    image: "https://placehold.co/300x200/4CAF50/FFFFFF?text=Water+Bottle",
    status: "lost",
    contact: "bob@university.edu",
  },
  {
    id: 6,
    title: "Red Sports Car",
    description: "Convertible sports car parked near gym",
    location: "Gym Parking Lot",
    date: "2024-01-10",
    image: "https://placehold.co/300x200/E53935/FFFFFF?text=Car",
    status: "found",
    contact: "charlie@university.edu",
  },
];

export const dummymessages = [
  {
    id: 1,
    sender: "John Smith",
    message: "Hi, I think this might be my iPhone. Can we meet at the library?",
    time: "2:30 PM",
    isMe: false,
  },
  {
    id: 2,
    sender: "You",
    message:
      "Sure! I can meet you there at 3 PM today. What's your phone case color?",
    time: "2:32 PM",
    isMe: true,
  },
  {
    id: 3,
    sender: "John Smith",
    message: "It's a black leather case with a small scratch on the back",
    time: "2:35 PM",
    isMe: false,
  },
];
